### ISSUE TITLE
`SysOutputInfo` serialization and refactoring `Features` 

### ISSUE THREAD

**Issue by lyuyangh** [neulab/ExplainaBoard#267] opened 2022-04-25 22:33 UTC
These are the things we discussed in https://github.com/neulab/explainaboard_web/pull/135 

- [ ] provide serialization and deserialization methods for `SysOutputInfo`. `SysOutputInfo` needs to be stored in the DB so we need a way to convert it into a dict. This is currently implemented in explainaboard_web but it's buggy. It'll be great if we can move it to this repo so it's always up to date. `SysOutputInfo` is pretty complex so it'll be great if we have unit tests for it too.
- [ ] add type annotation for Features class. My guess is it's something like this.
```
class Features(dict[str, FeatureType])
   ...
```
- Could we use inheritance to "group" Sequence, Span, Value and Set so we know they have overlaps in their attributes?
- `FeatureType` is a union of 7 different types with very different interfaces. It also includes dict, list, and tuple which are very general types so I think that may be a little difficult to maintain. I looked through the `default_features()` methods for all the tasks and I couldn't find where these types are used (dict, list, tuple). Could you please point me to where these types are used?

**Comment by neubig** [comment] 2022-04-26 00:11
Regarding serializing and deserializing SysOutputInfo. I think the following may work?
* serialization: whatever is used by json serialization, since we already have it for generating reports
* deserialization: `from_dict` https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/info.py#L231

**Comment by odashi** [comment] 2022-10-14 16:27
Duplicate of #446

**Closed by odashi** 2022-10-14 16:27 UTC
