### ISSUE TITLE
Introducing a unified & general interface for class serialization

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#302] opened 2022-05-12 15:25 UTC
It's good to consider introducing a unified & general interface for `from_dict`

Some existing implementation & discussion
* https://github.com/neulab/ExplainaBoard/blob/aaf91a57f4a5c143a6f6c2aec33a81a3e51690b8/explainaboard/utils/serialization.py#L4
* https://github.com/neulab/ExplainaBoard/pull/301
* https://github.com/neulab/ExplainaBoard/blob/aaf91a57f4a5c143a6f6c2aec33a81a3e51690b8/explainaboard/feature.py#L43

**Comment by odashi** [comment] 2022-10-14 10:11
Duplicate of #446, close anyway

**Closed by odashi** 2022-10-14 10:11 UTC
