### ISSUE TITLE
New Scenario: Multilingual Analysis

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#100] opened 2022-02-22 17:15 UTC
System analysis in multilingual setting is usually very painful especially for some one like me who is not a multilinguist.
We probably need some new designs.

**Comment by neubig** [comment] 2022-04-02 16:56
Duplicate of https://github.com/neulab/ExplainaBoard/issues/44

**Closed by neubig** 2022-04-02 16:56 UTC
